services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./.deploy/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./.deploy/nginx/conf.d:/etc/nginx/conf.d/"
      - "certificates:/etc/letsencrypt/"
      - "challenges:/var/www/certbot/"
    healthcheck:
      test: [ "CMD", "nc", "-z", "nginx", "80" ]
      interval: 30s
      timeout: 30s
      start_period: 10s
      retries: 10
    restart: unless-stopped
    networks:
      - proxy-network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - "certificates:/etc/letsencrypt/"
      - "challenges:/var/www/certbot/"
    networks:
      - proxy-network

# SHARED SETTINGS
networks:
  proxy-network:
    name: proxy-network
    driver: bridge

volumes:
  certificates: { }
  challenges: { }