services:
  # NGINX
  nginx:
    image: nginx:alpine
    ports:
      - "${DEPLOYMENT_PROXY_PORT}:80"
    volumes:
      - "./:/var/www"
      - "./.deploy/nginx/dev:/etc/nginx/conf.d/"
      - "${APP_STORAGE_PATH}:/mnt/storage"
    networks:
      - lemp_network

  # FPM
  fpm:
    user: "1000:1000"
    build:
      context: ..
      dockerfile: ../.deploy/fpm/Dockerfile
      args:
        app_mode: dev
    image: testtask-fpm-dev
    volumes:
      - "./:/var/www"
      - "${APP_STORAGE_PATH}:/mnt/storage"
    networks:
      - lemp_network

  # MYSQL
  mysql:
    image: mysql:9.0.1
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    networks:
      - lemp_network

  # REDIS
  redis:
    image: "redis:alpine"
    ports:
      - "6333:6379"
    networks:
      - lemp_network

  # SCHEDULER
  scheduler:
    image: testtask-fpm-dev
    command: [ "php", "artisan", "schedule:work" ]
    volumes:
      - "./:/var/www"
      - "${APP_STORAGE_PATH}:/mnt/storage"
    networks:
      - lemp_network
    depends_on:
      - fpm

  # RABBITMQ
  rabbitmq:
    image: rabbitmq:3.13.7-management
    ports:
      - "5677:5672"
      - "15677:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    networks:
      - lemp_network

networks:
  lemp_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  rabbitmq_data:
    driver: local
